### ISSUE TITLE
[TASK] Implement real inertia and damping matrix for Freya

### ISSUE THREAD

**Issue by Andeshog** [vortexntnu/vortex-asv#164]
### Description of task

The system matrices M and D for Freya should be improved to get values that better reflects reality.

### Suggested Workflow

- [ ] Take a look at the Otter of Maritime Robotics, as it is similar to Freya. https://github.com/cybergalactic/PythonVehicleSimulator/blob/master/src/python_vehicle_simulator/vehicles/otter.py

### Code Quality

- [ ] Every function in header files are documented (inputs/returns/exceptions)
- [ ] The project has automated tests that cover MOST of the functions and branches in functions (pytest/gtest)
- [ ] The code is documented on the wiki (provide link)

**Comment by alekskl01** [comment]
Is this finished?

**Comment by Andeshog** [comment]
> Is this finished?

Not yet, will try to finish it today
