### ISSUE TITLE
asv simulator failed to run

### ISSUE THREAD

**Issue by ronjakr** [vortexntnu/Vortex-ASV#21]
![image](https://user-images.githubusercontent.com/79790461/151199426-3615e864-f05f-4efd-ac56-3a70fa61283d.png)

Most likely due to not having gazebo on computer

**Comment by chrstrom** [comment]
Appears to be an error with allocation for displaying graphics. Need to look into the source of "x error of failed request badalloc (insufficient resources for operation)"

**Comment by ronjakr** [comment]
![image](https://user-images.githubusercontent.com/79790461/151663016-28249e43-2bf3-4ee2-b9de-731aab3ea5aa.png)
Simulator runs on a clean ros melodic image, with the required components installed. Issue may lie in the compose file for the simulator

**Comment by chrstrom** [comment]
Update: this may actually be an AMD mobile graphics problem

**Comment by chrstrom** [comment]
Containerized simulator runs headless so this won't be a problem 🚀
