### ISSUE TITLE
Collision avoidance

### ISSUE THREAD

**Issue by ronjakr** [vortexntnu/vortex-asv#61]
**Time estimate:** 40
**Deadline:** (hopefully) end of arbeidsuke

**Description of task:**
Implement functionality (on the auto side) for avoiding static and moving objects. Includes cooperation with perception to create an interface between the tracking and avoiding parts.

**Comment by ronjakr** [comment]
Current status:
Will be using the velocity obstacles method.
Interface with perception will be something alike the landmarks server for the AUV, but will include static and dynamic objects.

**Comment by eliasaar** [comment]
VO computational module has been implemented

**Comment by oskarhelgerud890** [comment]
Implemented code about VO functionality. Currently testing and tuning.
